name: versioning

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # ★これが重要

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'auto: version update')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: バージョン生成
        run: |
          DATE=$(date +%Y%m%d)
          HASH=$(git rev-parse --short HEAD)
          VERSION="rev_${DATE}_${HASH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: kanban.js更新
        run: |
          sed -i "s/^const APP_VERSION = .*/const APP_VERSION = \"${VERSION}\";/" addin/kanban/kanban.js

      - name: index.html更新
        run: |
          sed -i "s/^const VIEW_VERSION = .*/const VIEW_VERSION = \"${VERSION}\";/" addin/kanban/index.html

      - name: commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto: version update ${VERSION}" || echo "no changes"
          git push